# I looked at https://github.com/microsoft/cpprestsdk/blob/master/azure-pipelines.yml

jobs:
  - job: Windows_VS2017_x64
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: git submodule update --init --recursive
      displayName: Checking out submodules
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6' 
        addToPath: true 
        architecture: 'x64' 
    #- script: cinst innosetup
    #  displayName: Installing Innosetup
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '-A x64 ' #-DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 ..'      
